// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesisTIC.Infrastructure.Persistence;

#nullable disable

namespace TesisTIC.Infrastructure.Migrations
{
    [DbContext(typeof(TesisTICDbContext))]
    [Migration("20260421223639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesisTIC.Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Horas")
                        .HasColumnType("integer");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("FechaAtualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroEmpleado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Propuesta creada, pendiente de revisión",
                            FechaCreacion = new DateTime(2026, 4, 21, 22, 36, 38, 386, DateTimeKind.Utc).AddTicks(1861),
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Propuesta enviada para revisión por CPGIC",
                            FechaCreacion = new DateTime(2026, 4, 21, 22, 36, 38, 386, DateTimeKind.Utc).AddTicks(1865),
                            Nombre = "Enviada"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Propuesta bajo revisión",
                            FechaCreacion = new DateTime(2026, 4, 21, 22, 36, 38, 386, DateTimeKind.Utc).AddTicks(1867),
                            Nombre = "En Revisión"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Propuesta aprobada",
                            FechaCreacion = new DateTime(2026, 4, 21, 22, 36, 38, 386, DateTimeKind.Utc).AddTicks(1869),
                            Nombre = "Aprobada"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Propuesta rechazada",
                            FechaCreacion = new DateTime(2026, 4, 21, 22, 36, 38, 386, DateTimeKind.Utc).AddTicks(1870),
                            Nombre = "Rechazada"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Propuesta con observaciones, requiere ajustes",
                            FechaCreacion = new DateTime(2026, 4, 21, 22, 36, 38, 386, DateTimeKind.Utc).AddTicks(1871),
                            Nombre = "Observada"
                        });
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.LineaInvestigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("LineasInvestigacion");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstudianteAsignado")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumeroModulo")
                        .HasColumnType("integer");

                    b.Property<string>("Productos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropuestaId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.ObservacionModulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("ObservacionesModulos");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.ObservacionPropuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropuestaId");

                    b.ToTable("ObservacionesPropuestas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Propuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<string>("Facultad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnvioPrimera")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LineaInvestigacionId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroParticipantes")
                        .HasColumnType("integer");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Proyecto")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("LineaInvestigacionId");

                    b.ToTable("Propuestas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.PropuestaAsignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("PropuestaId", "AsignaturaId")
                        .IsUnique();

                    b.ToTable("PropuestasAsignaturas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.PropuestaEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("PropuestaId", "EstudianteId")
                        .IsUnique();

                    b.ToTable("PropuestasEstudiantes");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.RechazoPropuesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropuestaId")
                        .HasColumnType("integer");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropuestaId")
                        .IsUnique();

                    b.ToTable("RechazoPropuestas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.RechazoRazon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RechazoPropuestaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RechazoPropuestaId");

                    b.ToTable("RechazoRazones");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Actividades")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Propuesta", "Propuesta")
                        .WithMany("Modulos")
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.ObservacionModulo", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Observaciones")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.ObservacionPropuesta", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Propuesta", "Propuesta")
                        .WithMany("Observaciones")
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Propuesta", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Docente", "Docente")
                        .WithMany("Propuestas")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisTIC.Domain.Entities.Estado", "Estado")
                        .WithMany("Propuestas")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisTIC.Domain.Entities.LineaInvestigacion", "LineaInvestigacion")
                        .WithMany("Propuestas")
                        .HasForeignKey("LineaInvestigacionId");

                    b.Navigation("Docente");

                    b.Navigation("Estado");

                    b.Navigation("LineaInvestigacion");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.PropuestaAsignatura", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("PropuestasAsignadas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisTIC.Domain.Entities.Propuesta", "Propuesta")
                        .WithMany("AsignaturasAsignadas")
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.PropuestaEstudiante", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("PropuestasAsignadas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesisTIC.Domain.Entities.Propuesta", "Propuesta")
                        .WithMany("EstudiantesAsignados")
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.RechazoPropuesta", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.Propuesta", "Propuesta")
                        .WithOne("Rechazo")
                        .HasForeignKey("TesisTIC.Domain.Entities.RechazoPropuesta", "PropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.RechazoRazon", b =>
                {
                    b.HasOne("TesisTIC.Domain.Entities.RechazoPropuesta", "RechazoPropuesta")
                        .WithMany("Razones")
                        .HasForeignKey("RechazoPropuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RechazoPropuesta");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Asignatura", b =>
                {
                    b.Navigation("PropuestasAsignadas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("PropuestasAsignadas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.LineaInvestigacion", b =>
                {
                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.Propuesta", b =>
                {
                    b.Navigation("AsignaturasAsignadas");

                    b.Navigation("EstudiantesAsignados");

                    b.Navigation("Modulos");

                    b.Navigation("Observaciones");

                    b.Navigation("Rechazo");
                });

            modelBuilder.Entity("TesisTIC.Domain.Entities.RechazoPropuesta", b =>
                {
                    b.Navigation("Razones");
                });
#pragma warning restore 612, 618
        }
    }
}
